spring:
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config
  profiles:
    active: native
  application:
    name: config-server-local

server:
  port: 8769
