server:
  port: 8769

# 从git 仓库读取配置文件的配置项
# https://github.com/Air-TR/springcloud
# 目录已经上传config-client-dev.yml文件，该文件没有指定端口，只配置了foo 和 name变量
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Air-TR/springcloud
          searchPaths: config
          # 如果为公开仓库，用户名密码可不填
          username:
          password:
      label: master
  application:
    name: config-server-github

