#有多个不同Uri 地址（例如example.com、google.com 等）的服务实例，通过stores.ribbon.listOfServers 来配置这些服务实例的Uri
stores:
  ribbon:
    listOfServers: example.com,google.com,baidu.com

# 关闭通过eureka获取服务注册列表功能（Ribbon会默认从Eureka的服务注册列表中获取服务的信息，关闭后需要自己维护一份服务注册列表信息，也可以实现负载均衡）
ribbon:
  eureka:
    enabled: false

# 关闭eureka的自我注册功能
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

server:
  port: 8769
